services:
  - type: web
    name: exponentes-a1
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:socket_app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /
